//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario.GUI.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_formulario
    {
        public int id { get; set; }
        public string especialidad { get; set; }
        public string años_experiencia { get; set; }
        public string salario { get; set; }
        public System.DateTime fecha_envio { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string celular { get; set; }
        public Nullable<int> empresa_id { get; set; }
        public Nullable<int> persona_id { get; set; }
    
        public virtual tb_empresa tb_empresa { get; set; }
        public virtual tb_persona tb_persona { get; set; }
    }
}
